### PR TITLE
Add `color rand` for zsh

### LINKED ISSUE #94: Add a method to chose random `colors`-scheme
I [adapted](https://github.com/miallo/dotfiles/blob/f0561a151c02a4c58d3fb55d2c8123bab57ad3c0/.config/zsh/colors#L144-L146) your [colors](https://github.com/wincent/wincent/blob/master/aspects/dotfiles/files/.zsh/colors)-script and then I just wanted to explore the themes and so I added `colors rand [pattern]` which (as the name suggests) chooses a random color scheme. Are you interested in this? If not - just close this issue ;)

### PR DESCRIPTION
**Pull request by miallo**
For selecting a random color scheme run `color rand` or add another
pattern, like `color rand dark`. By default it will print the name of
the new color scheme, but you can surpress this by passing in `-q` or
`--quiet` before the (optional) pattern.

Fixes #94

### CODE REVIEW

**Comment by miallo** [comment]
Sorry for missing that - I changed the parsing of the args in [my implementation](https://github.com/miallo/dotfiles/blob/master/.config/zsh/colors#L47-L86) for a more explicit way...

**Comment by wincent** [comment]
Thanks @miallo; I squashed the commits and added some tweaks on top.

**Comment by miallo** [comment]
Sorry for the style issues - I should have done them myself...

Thanks again for your nice vim videos - I learned a lot from them!

**Comment by wincent** [comment]
Good to hear and thanks once again for the PR.

**Pull request closed without merging**
